### ISSUE TITLE
Remove ugly duplicate `FileNotFoundError` messages

### ISSUE THREAD

**Issue by zachtheclimber** [JaZa-Programming/ATS-Hacker#3]
Currently, when ATS-Hacker is run on the command line with an invalid filename, it prints two error messages, like seen here:
```Traceback (most recent call last):
  File "ats_hacker/api/import_file.py", line 13, in import_file
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'ats_hacker/tests/test_data/simple-job.tx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zachtheclimber/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zachtheclimber/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ats_hacker/__main__.py", line 4, in <module>
    app.run()
  File "ats_hacker/app.py", line 5, in run
    CLI.start()
  File "ats_hacker/cli/cli.py", line 20, in start
    interface._process_document(import_file(args.filename[0]))
  File "ats_hacker/api/import_file.py", line 16, in import_file
    raise FileNotFoundError(f'No such file or directory: {filename}')
FileNotFoundError: No such file or directory: ats_hacker/tests/test_data/simple-job.tx
```

This is ugly and should not be how the error is presented to the user.

**Comment by zachtheclimber** [comment]
This issue is resolved with commit [5ff39](https://github.com/JaZa-Programming/ATS-Hacker/commit/5ff39997b0da065414aee83bfaef90f9b94ab7f7).
